# Generated by Django 4.2.3 on 2023-07-27 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='User',
        ),
    ]
