# Generated by Django 4.2.3 on 2023-07-30 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0006_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
