# Generated by Django 4.2.3 on 2023-07-31 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0012_remove_comment_date_alter_comment_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(choices=[('Laptop', 'Laptop'), ('accessories', 'Accessories'), ('Iron', 'Iron')], max_length=50)),
                ('product_desc', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('product_image', models.ImageField(upload_to='product_image')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a1.user')),
            ],
        ),
    ]
