# Generated by Django 4.2.3 on 2023-07-31 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0013_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
