# Generated by Django 4.2.3 on 2023-07-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0015_product_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.PositiveIntegerField(),
        ),
    ]
